import { icons } from "./icons";

export const tabs: AppTab[] = [
  { name: "index", title: "Início", icon: icons.home },
  { name: "subscriptions", title: "Assinaturas", icon: icons.wallet },
  { name: "insights", title: "Insights", icon: icons.activity },
  { name: "settings", title: "Configurações", icon: icons.setting },
];

export const HOME_USER = {
  name: "João | Desenvolvedor",
};

export const HOME_BALANCE = {
  amount: 785.4,
  nextRenewalDate: "2026-03-18T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
  {
    id: "spotify",
    icon: icons.spotify,
    name: "Spotify",
    price: 21.9,
    currency: "BRL",
    daysLeft: 2,
  },
  {
    id: "notion",
    icon: icons.notion,
    name: "Notion",
    price: 59.9,
    currency: "BRL",
    daysLeft: 4,
  },
  {
    id: "figma",
    icon: icons.figma,
    name: "Figma",
    price: 89.9,
    currency: "BRL",
    daysLeft: 6,
  },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "adobe-creative-cloud",
    icon: icons.adobe,
    name: "Adobe Creative Cloud",
    plan: "Todos os Apps",
    category: "Design",
    paymentMethod: "Visa final 8530",
    status: "ativo",
    startDate: "2025-03-20T10:00:00.000Z",
    price: 275.0,
    currency: "BRL",
    billing: "Mensal",
    renewalDate: "2026-03-20T10:00:00.000Z",
    color: "#f5c542",
  },
  {
    id: "github-pro",
    icon: icons.github,
    name: "GitHub Pro",
    plan: "Desenvolvedor",
    category: "Ferramentas Dev",
    paymentMethod: "Mastercard final 2408",
    status: "ativo",
    startDate: "2024-11-24T10:00:00.000Z",
    price: 24.9,
    currency: "BRL",
    billing: "Mensal",
    renewalDate: "2026-03-24T10:00:00.000Z",
    color: "#e8def8",
  },
  {
    id: "claude-pro",
    icon: icons.claude,
    name: "Claude Pro",
    plan: "Plano Pro",
    category: "Ferramentas IA",
    paymentMethod: "Amex final 1010",
    status: "pausado",
    startDate: "2025-06-27T10:00:00.000Z",
    price: 110.0,
    currency: "BRL",
    billing: "Mensal",
    renewalDate: "2026-03-27T10:00:00.000Z",
    color: "#b8d4e3",
  },
  {
    id: "canva-pro",
    icon: icons.canva,
    name: "Canva Pro",
    plan: "Acesso Anual",
    category: "Design",
    paymentMethod: "Visa final 7784",
    status: "cancelado",
    startDate: "2024-04-02T10:00:00.000Z",
    price: 329.9,
    currency: "BRL",
    billing: "Anual",
    renewalDate: "2026-04-02T10:00:00.000Z",
    color: "#b8e8d0",
  },
];

export const ALL_SUBSCRIPTIONS: Subscription[] = [
  ...HOME_SUBSCRIPTIONS,
  {
    id: "spotify-premium",
    icon: icons.spotify,
    name: "Spotify Premium",
    plan: "Individual",
    category: "Música & Streaming",
    paymentMethod: "Nubank final 1234",
    status: "ativo",
    startDate: "2024-01-15T10:00:00.000Z",
    price: 21.9,
    currency: "BRL",
    billing: "Mensal",
    renewalDate: "2026-03-15T10:00:00.000Z",
    color: "#c7f0db",
  },
  {
    id: "notion-plus",
    icon: icons.notion,
    name: "Notion Plus",
    plan: "Plus",
    category: "Produtividade",
    paymentMethod: "Visa final 8530",
    status: "ativo",
    startDate: "2024-08-10T10:00:00.000Z",
    price: 59.9,
    currency: "BRL",
    billing: "Mensal",
    renewalDate: "2026-03-10T10:00:00.000Z",
    color: "#e2e8f0",
  },
  {
    id: "figma-professional",
    icon: icons.figma,
    name: "Figma Professional",
    plan: "Profissional",
    category: "Design",
    paymentMethod: "Mastercard final 2408",
    status: "ativo",
    startDate: "2024-05-12T10:00:00.000Z",
    price: 89.9,
    currency: "BRL",
    billing: "Mensal",
    renewalDate: "2026-03-12T10:00:00.000Z",
    color: "#fed7aa",
  },
  {
    id: "chatgpt-plus",
    icon: icons.openai,
    name: "ChatGPT Plus",
    plan: "Plus",
    category: "Ferramentas IA",
    paymentMethod: "Visa final 7784",
    status: "ativo",
    startDate: "2024-02-20T10:00:00.000Z",
    price: 119.9,
    currency: "BRL",
    billing: "Mensal",
    renewalDate: "2026-03-20T10:00:00.000Z",
    color: "#d1fae5",
  },
  {
    id: "dropbox-plus",
    icon: icons.dropbox,
    name: "Dropbox Plus",
    plan: "2 TB Storage",
    category: "Armazenamento",
    paymentMethod: "Visa final 8530",
    status: "pausado",
    startDate: "2023-10-01T10:00:00.000Z",
    price: 69.9,
    currency: "BRL",
    billing: "Mensal",
    renewalDate: "2026-03-01T10:00:00.000Z",
    color: "#bfdbfe",
  },
  {
    id: "medium-member",
    icon: icons.medium,
    name: "Medium Member",
    plan: "Leitura Ilimitada",
    category: "Leitura & Mídia",
    paymentMethod: "Mastercard final 2408",
    status: "ativo",
    startDate: "2024-03-05T10:00:00.000Z",
    price: 29.9,
    currency: "BRL",
    billing: "Mensal",
    renewalDate: "2026-03-05T10:00:00.000Z",
    color: "#f3f4f6",
  },
];
